name = input("Enter the name of the student: ")
age = int(input("Enter the age of the student: "))
rollNumber = int(input("Enter the roll number of the student: "))
gender = input("Enter the gender of the student: ")
marks1 = int(input("Enter the first subject marks: "))
marks2 = int(input("Enter the second subject marks: "))
marks3 = int(input("Enter the third subject marks: "))
averageMarks = (marks1+marks2+marks3)/3
print("Name of the student is: ",name)
print("Age of the student is: ",age)
print("Roll Number of the student is: ",rollNumber)
print("Gender of the student is: ",gender)
print("Average marks of the student is: ",averageMarks)
print("Type of variable name is: ",type(name))
print("Type of variable age is: ",type(age))
print("Type of variable rollNumber is: ",type(rollNumber))
print("Type of variable gender is: ",type(gender))
print("Type of variable averageMarks is: ",type(averageMarks))
